// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-b3gfpOPPq29hf-iS-Fa0F-lSrcI1C2k',
    appId: '1:755850237380:web:d4d4c4b3823abae6044091',
    messagingSenderId: '755850237380',
    projectId: 'fixnow-app-75722',
    authDomain: 'fixnow-app-75722.firebaseapp.com',
    storageBucket: 'fixnow-app-75722.firebasestorage.app',
    measurementId: 'G-VSZKG42XGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpJJoLXxDRBq_gACukjRtwSdCD8SllQLM',
    appId: '1:755850237380:android:9cdb8dd6b135dc2b044091',
    messagingSenderId: '755850237380',
    projectId: 'fixnow-app-75722',
    databaseURL:
      'https://fixnow-app-75722-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fixnow-app-75722.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyhUMVvnI0A1Hs9h4lYt85rzHX9a72Hoo',
    appId: '1:755850237380:ios:f7e4db1ab800841b044091',
    messagingSenderId: '755850237380',
    projectId: 'fixnow-app-75722',
    storageBucket: 'fixnow-app-75722.firebasestorage.app',
    iosBundleId: 'com.example.fixNowApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyhUMVvnI0A1Hs9h4lYt85rzHX9a72Hoo',
    appId: '1:755850237380:ios:f7e4db1ab800841b044091',
    messagingSenderId: '755850237380',
    projectId: 'fixnow-app-75722',
    storageBucket: 'fixnow-app-75722.firebasestorage.app',
    iosBundleId: 'com.example.fixNowApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-b3gfpOPPq29hf-iS-Fa0F-lSrcI1C2k',
    appId: '1:755850237380:web:870cdc71f2992d69044091',
    messagingSenderId: '755850237380',
    projectId: 'fixnow-app-75722',
    authDomain: 'fixnow-app-75722.firebaseapp.com',
    storageBucket: 'fixnow-app-75722.firebasestorage.app',
    measurementId: 'G-Z4QJPYWEQZ',
  );
}
